web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./web/static:/www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432:5432"